import fields = require("./schema/defaultSchemaFields");
import routes = require("./schema/defaultSchemaRoutes");
import pagination = require("./schema/defaultSchemaPagination");
import wrappers = require("./schema/defaultSchemaWrappers");
export declare const filters: {};
export declare const middleware: {};
export declare const routeKeys: string[];
export declare const hooks: {};
export declare const saveNullInputsInDatabase: boolean;
export declare const returnNullValuesInResponse: boolean;
export { fields, routes, pagination, wrappers };
